### ISSUE TITLE
Explore Visual Studio Code Remote Dev Containers on AWS

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#159]
I'm working on a MBP from 2020 while traveling, which has lower specs compared to my workstation at home. As a results, operations are slower on the MBP. For instance, installing the npm dependencies took 30 min instead of 5 min on my PC (I need to try again as this may have been a fluke). Rong and Verena have also reported issues related to working with limited compute resources (see #158 ).

## Task

I would like developers in the team to enjoy developing with similar, responsive environments.

1. Benchmark the runtime of the operations like yarn install, lint, build test. on current team machines.
2. Identify a suitable AWS instance that reduce the above runtime (pick an instance from the service catalog?)
3. Setup [Visual Studio Code Remote Dev Containers on AWS Set Up Guide](https://blog.doppler.com/visual-studio-code-remote-dev-containers-on-aws) or similar solution.

**Comment by tschaffter** [comment]
- https://sagebionetworks.jira.com/wiki/spaces/IT/pages/996376579/Connect+to+Provisioned+Instances
- https://aws.amazon.com/emr/pricing/

**Comment by tschaffter** [comment]
## Protocol

- [ ] Create EC2 instance `m5.2xlarge` (TODO: add spec)
- [ ] SSH to the instance (requires to be connected to Sage VPN)

**Comment by tschaffter** [comment]
## Issue when running dev container on EC2 for the first time

- Open VS Code
- `Remote-containers: Open Folder in Container...`

Error:

```console
Removing intermediate container 2e6d191cf446
 ---> c44440588e78
Successfully built c44440588e78
Successfully tagged vsc-challenge-registry-33c8de79574d448bbfa608795a7e04bc-features-uid:latest

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
[74303 ms] Start: Run: docker -v
[75487 ms] Start: Run: docker events --format {{json .}} --filter event=start
[75490 ms] Start: Starting container
[75490 ms] Start: Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/home/tschaffter/dev2/tschaffter/challenge-registry,target=/workspaces/challenge-registry --mount type=volume,src=dind-var-lib-docker,dst=/var/lib/docker --mount type=volume,src=vscode,dst=/vscode -l vsch.local.folder=\\wsl$\Debian\home\tschaffter\dev2\tschaffter\challenge-registry -l vsch.quality=stable --privileged --entrypoint /bin/sh vsc-challenge-registry-33c8de79574d448bbfa608795a7e04bc-features-uid -c echo Container started
docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /home/tschaffter/dev2/tschaffter/challenge-registry.
See 'docker run --help'.
[77086 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=\\wsl$\Debian\home\tschaffter\dev2\tschaffter\challenge-registry --filter label=vsch.quality=stable
[78260 ms] Error: Command failed: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/home/tschaffter/dev2/tschaffter/challenge-registry,target=/workspaces/challenge-registry --mount type=volume,src=dind-var-lib-docker,dst=/var/lib/docker --mount type=volume,src=vscode,dst=/vscode -l vsch.local.folder=\\wsl$\Debian\home\tschaffter\dev2\tschaffter\challenge-registry -l vsch.quality=stable --privileged --entrypoint /bin/sh vsc-challenge-registry-33c8de79574d448bbfa608795a7e04bc-features-uid -c echo Container started
[78261 ms] trap "exit 0" 15
[78261 ms] /usr/local/share/docker-init.sh
[78261 ms] exec "$@"
[78261 ms] while sleep 1 & wait $!; do :; done -
[78261 ms]     at IR (/home/tschaffter/.vscode-remote-containers/dist/dev-containers-cli-0.234.0/dist/spec-node/devContainersSpecCLI.js:221:995)
[78261 ms]     at zy (/home/tschaffter/.vscode-remote-containers/dist/dev-containers-cli-0.234.0/dist/spec-node/devContainersSpecCLI.js:221:933)
[78261 ms]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[78261 ms]     at async $R (/home/tschaffter/.vscode-remote-containers/dist/dev-containers-cli-0.234.0/dist/spec-node/devContainersSpecCLI.js:226:2007)
[78261 ms]     at async Zy (/home/tschaffter/.vscode-remote-containers/dist/dev-containers-cli-0.234.0/dist/spec-node/devContainersSpecCLI.js:226:3112)
[78261 ms]     at async BR (/home/tschaffter/.vscode-remote-containers/dist/dev-containers-cli-0.234.0/dist/spec-node/devContainersSpecCLI.js:226:12448)
[78261 ms]     at async qR (/home/tschaffter/.vscode-remote-containers/dist/dev-containers-cli-0.234.0/dist/spec-node/devContainersSpecCLI.js:226:12204)
[78263 ms] Exit code 1
[78266 ms] Command failed: /home/tschaffter/.vscode-remote-containers/bin/57fd6d0195bb9b9d1b49f6da5db789060795de47/node /home/tschaffter/.vscode-remote-containers/dist/dev-containers-cli-0.234.0/dist/spec-node/devContainersSpecCLI.js up --container-data-folder .vscode-server/data/Machine --container-system-data-folder /var/vscode-server --workspace-folder /home/tschaffter/dev2/tschaffter/challenge-registry --workspace-mount-consistency cached --id-label vsch.local.folder=\\wsl$\Debian\home\tschaffter\dev2\tschaffter\challenge-registry --id-label vsch.quality=stable --log-level debug --log-format json --config /home/tschaffter/dev2/tschaffter/challenge-registry/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[78266 ms] Exit code 1
```

**Comment by tschaffter** [comment]
## Issue when running the sample container on EC2

```console
Remote-Containers: Try a Development Container Sample...
```

Error:

```console

```

This error is different from the one posted above. Not sure why as the only difference would be the image used?

The Docker version on the EC2 is not the issue:

```console
$ docker --version
Docker version 20.10.15, build fd82621
```

**Comment by tschaffter** [comment]
## Issue when running dev container on EC2 for the first time (Mac)

Docker context endpoint: `ssh://ubuntu@devcontainers`

Error in VS Code:

```console
Failed to connect to the remote extension host server (Error: )
```

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/3056480/167677977-485cf020-a958-4378-9052-7eabbdca155a.png">

The error is similar to the error encountered with WSL.

**Comment by tschaffter** [comment]
> Docker does not support mounting (binding) your local filesystem into a remote container, so Visual Studio Code's default devcontainer.json behavior to use your local source code will not work.

Source: https://code.visualstudio.com/remote/advancedcontainers/develop-remote-host

**Comment by vpchung** [comment]
### Verena's local dev environment

(vc/n: prepare to be amazed by my machine's numbers...... 😅 )

```console
$ nproc
4
```

```console
$ cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 142
model name      : Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
stepping        : 10
cpu MHz         : 2399.714
cache size      : 6144 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch fsgsbase bmi1 smep bmi2 erms rdseed adx smap clflushopt arat
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit srbds
bogomips        : 4799.42
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 142
model name      : Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
stepping        : 10
cpu MHz         : 2399.714
cache size      : 6144 KB
physical id     : 1
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch fsgsbase bmi1 smep bmi2 erms rdseed adx smap clflushopt arat
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit srbds
bogomips        : 5739.42
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:

processor       : 2
vendor_id       : GenuineIntel
cpu family      : 6
model           : 142
model name      : Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
stepping        : 10
cpu MHz         : 2399.714
cache size      : 6144 KB
physical id     : 2
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 2
initial apicid  : 2
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch fsgsbase bmi1 smep bmi2 erms rdseed adx smap clflushopt arat
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit srbds
bogomips        : 5861.15
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:

processor       : 3
vendor_id       : GenuineIntel
cpu family      : 6
model           : 142
model name      : Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
stepping        : 10
cpu MHz         : 2399.714
cache size      : 6144 KB
physical id     : 3
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 3
initial apicid  : 3
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch fsgsbase bmi1 smep bmi2 erms rdseed adx smap clflushopt arat
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit srbds
bogomips        : 6061.58
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:

```

```console
$ cat /proc/meminfo 
MemTotal:        6087024 kB
MemFree:         1952648 kB
MemAvailable:    4229696 kB
Buffers:          126628 kB
Cached:          2402484 kB
SwapCached:            0 kB
Active:           674036 kB
Inactive:        2939068 kB
Active(anon):      80272 kB
Inactive(anon):  1359028 kB
Active(file):     593764 kB
Inactive(file):  1580040 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:       1048572 kB
SwapFree:        1048572 kB
Dirty:                 0 kB
Writeback:             0 kB
AnonPages:       1081480 kB
Mapped:           337900 kB
Shmem:            355308 kB
KReclaimable:     401044 kB
Slab:             456584 kB
SReclaimable:     401044 kB
SUnreclaim:        55540 kB
KernelStack:        9872 kB
PageTables:        22552 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     4092084 kB
Committed_AS:    4662788 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       12924 kB
VmallocChunk:          0 kB
Percpu:             2352 kB
AnonHugePages:     14336 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
FileHugePages:         0 kB
FilePmdMapped:         0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:               0 kB
DirectMap4k:       81920 kB
DirectMap2M:     6209536 kB
```

```console
$ hyperfine --warmup 1 --runs 10 'nx run-many --all --target=lint --skip-nx-cache'
Benchmark 1: nx run-many --all --target=lint --skip-nx-cache
  Time (mean ± σ):     208.930 s ± 23.821 s    [User: 129.407 s, System: 40.182 s]
  Range (min … max):   189.249 s … 255.607 s    10 runs
```

```console
$ hyperfine --warmup 1 --runs 10 'nx run-many --all --target=test --skip-nx-cache'
Benchmark 1: nx run-many --all --target=test --skip-nx-cache
  Time (mean ± σ):     196.203 s ± 18.329 s    [User: 176.400 s, System: 51.913 s]
  Range (min … max):   182.172 s … 236.834 s    10 runs
```

```console
$ hyperfine --warmup 1 --runs 10 'nx run-many --all --target=build --skip-nx-cache'
Benchmark 1: nx run-many --all --target=build --skip-nx-cache
  Time (mean ± σ):     117.091 s ± 15.111 s    [User: 81.702 s, System: 16.255 s]
  Range (min … max):   102.099 s … 138.756 s    10 runs
```

```console
$ hyperfine --warmup 1 --runs 10 'nx test api --skip-nx-cache'
Benchmark 1: nx test api --skip-nx-cache
  Time (mean ± σ):     29.570 s ±  1.826 s    [User: 10.831 s, System: 2.059 s]
  Range (min … max):   27.136 s … 32.872 s    10 runs
```

```console
$ hyperfine --warmup 1 --runs 10 'nx test web-ui --skip-nx-cache'
Benchmark 1: nx test web-ui --skip-nx-cache
  Time (mean ± σ):     42.975 s ±  0.741 s    [User: 29.003 s, System: 7.017 s]
  Range (min … max):   42.156 s … 44.662 s    10 runs
```

```console
$ speedtest
Retrieving speedtest.net configuration...
Testing from Amazon.com (52.44.61.21)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by All Points Broadband (Ashburn, VA) [0.43 km]: 122.346 ms
Testing download speed................................................................................
Download: 52.12 Mbit/s
Testing upload speed......................................................................................................
Upload: 15.60 Mbit/s
```

**Comment by rrchai** [comment]
### Rong's local dev environment

```console
$ nproc
4
```

```console
$ cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 142
model name      : Intel(R) Core(TM) i7-8557U CPU @ 1.70GHz
stepping        : 10
cpu MHz         : 1700.000
cache size      : 8192 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 22
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht pbe syscall nx pdpe1gb lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid pni pclmulqdq dtes64 ds_cpl ssse3 sdbg fma cx16 xtpr pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch fsgsbase bmi1 avx2 bmi2 erms xsaveopt arat
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit srbds
bogomips        : 3400.00
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 142
model name      : Intel(R) Core(TM) i7-8557U CPU @ 1.70GHz
stepping        : 10
cpu MHz         : 1700.000
cache size      : 8192 KB
physical id     : 1
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 22
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht pbe syscall nx pdpe1gb lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid pni pclmulqdq dtes64 ds_cpl ssse3 sdbg fma cx16 xtpr pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch fsgsbase bmi1 avx2 bmi2 erms xsaveopt arat
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit srbds
bogomips        : 3395.67
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:

processor       : 2
vendor_id       : GenuineIntel
cpu family      : 6
model           : 142
model name      : Intel(R) Core(TM) i7-8557U CPU @ 1.70GHz
stepping        : 10
cpu MHz         : 1700.000
cache size      : 8192 KB
physical id     : 2
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 2
initial apicid  : 2
fpu             : yes
fpu_exception   : yes
cpuid level     : 22
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht pbe syscall nx pdpe1gb lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid pni pclmulqdq dtes64 ds_cpl ssse3 sdbg fma cx16 xtpr pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch fsgsbase bmi1 avx2 bmi2 erms xsaveopt arat
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit srbds
bogomips        : 3408.55
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:

processor       : 3
vendor_id       : GenuineIntel
cpu family      : 6
model           : 142
model name      : Intel(R) Core(TM) i7-8557U CPU @ 1.70GHz
stepping        : 10
cpu MHz         : 1700.000
cache size      : 8192 KB
physical id     : 3
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 3
initial apicid  : 3
fpu             : yes
fpu_exception   : yes
cpuid level     : 22
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht pbe syscall nx pdpe1gb lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid pni pclmulqdq dtes64 ds_cpl ssse3 sdbg fma cx16 xtpr pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch fsgsbase bmi1 avx2 bmi2 erms xsaveopt arat
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit srbds
bogomips        : 3403.00
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:
```

```console
$ cat /proc/meminfo 
MemTotal:        4028788 kB
MemFree:         2523316 kB
MemAvailable:    2688016 kB
Buffers:           39336 kB
Cached:           610196 kB
SwapCached:         7016 kB
Active:           465136 kB
Inactive:         860624 kB
Active(anon):     245432 kB
Inactive(anon):   745112 kB
Active(file):     219704 kB
Inactive(file):   115512 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:       1048572 kB
SwapFree:         715592 kB
Dirty:                96 kB
Writeback:             0 kB
AnonPages:        670256 kB
Mapped:           154212 kB
Shmem:            316036 kB
KReclaimable:      68500 kB
Slab:             124440 kB
SReclaimable:      68500 kB
SUnreclaim:        55940 kB
KernelStack:       10864 kB
PageTables:        13944 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     3062964 kB
Committed_AS:    6831656 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       12732 kB
VmallocChunk:          0 kB
Percpu:             2464 kB
AnonHugePages:      4096 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
FileHugePages:         0 kB
FilePmdMapped:         0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:               0 kB
DirectMap4k:       65536 kB
DirectMap2M:     3080192 kB
DirectMap1G:     3145728 kB
```

```console
$ hyperfine --warmup 1 --runs 10 'nx run-many --all --target=lint --skip-nx-cache'
Benchmark 1: nx run-many --all --target=lint --skip-nx-cache
  Time (mean ± σ):     183.774 s ± 10.668 s    [User: 137.248 s, System: 50.949 s]
  Range (min … max):   162.213 s … 199.050 s    10 runs
```

```console
$ hyperfine --warmup 1 --runs 10 'nx run-many --all --target=test --skip-nx-cache'
Benchmark 1: nx run-many --all --target=test --skip-nx-cache
  Time (mean ± σ):     162.171 s ±  8.294 s    [User: 167.960 s, System: 56.651 s]
  Range (min … max):   148.207 s … 173.731 s    10 runs
```

```console
$ hyperfine --warmup 1 --runs 10 'nx run-many --all --target=build --skip-nx-cache'

```

```console
$ hyperfine --warmup 1 --runs 10 'nx test api --skip-nx-cache'

```

```console
$ hyperfine --warmup 1 --runs 10 'nx test web-ui --skip-nx-cache'

```

```console
$ speedtest

```

**Comment by tschaffter** [comment]
The next task is to describe how to setup the EC2. This work is tracked in #172.
