### ISSUE TITLE
Fix inconsistent `node_modules/canvas` versions

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#175]
The testing suite of TS projects fails with the following error:

```console
$ nx run-many --all --target=test --skip-nx-cache


    ✖  nx run web-challenge-search:test
 FAIL   web-challenge-search  libs/web/challenge-search/src/lib/challenge-search.component.spec.ts
  ● Test suite failed to run
       
           The module '/workspaces/challenge-registry/node_modules/canvas/build/Release/canvas.node'
           was compiled against a different Node.js version using
           NODE_MODULE_VERSION 83. This version of Node.js requires
           NODE_MODULE_VERSION 93. Please try re-compiling or re-installing
           the module (for instance, using `npm rebuild` or `npm install`).
       
             at Object.<anonymous> (../../../node_modules/canvas/lib/bindings.js:3:18)
       
----------|---------|----------|---------|---------|-------------------
       File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
       ----------|---------|----------|---------|---------|-------------------
       All files |       0 |        0 |       0 |       0 |                   
       ----------|---------|----------|---------|---------|-------------------
       Test Suites: 1 failed, 1 total
       Tests:       0 total
       Snapshots:   0 total
       Time:        0.174 s
       Ran all test suites.
       
    ✔  nx run shared-web-components:test (1s)
    ✔  nx run web-user-profile:test (1s)

    ✖  nx run web-org-profile:test
 FAIL   web-org-profile  libs/web/org-profile/src/lib/org-profile-data-service.service.spec.ts
  ● Test suite failed to run
       
           The module '/workspaces/challenge-registry/node_modules/canvas/build/Release/canvas.node'
           was compiled against a different Node.js version using
           NODE_MODULE_VERSION 83. This version of Node.js requires
           NODE_MODULE_VERSION 93. Please try re-compiling or re-installing
           the module (for instance, using `npm rebuild` or `npm install`).
       
             at Object.<anonymous> (../../../node_modules/canvas/lib/bindings.js:3:18)
...
```

**Comment by tschaffter** [comment]
This error occurred to Verena and I when working outside of the devcontainer. I have node v14 on my host and we use v16 in the devcontainer. In this case, the error occurred because I try to run the tests with node v14 when the project dependencies were installed from the devcontainer using node v16.

**Comment by tschaffter** [comment]
## Update 2022-12-27

I had the same issue today when pushing the Schematic Ng app. The reason is because the GitHub cache had a version of Canvas built with Node v16. Since then, we have upgraded the dev container to use Node v18.

The solution was to comment the line below and push the commit. The commit should then successfully pass the checks.

```yaml
      - name: Install Node.js dependencies
        # if: steps.cache-node.outputs.cache-hit != 'true'
        run: yarn install --immutable
```

Finally, undo the above change and push the new commit to use again the cache.
