### ISSUE TITLE
Place detached services in the same docker network when starting them with `serve-detach`

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#296]
For example, the Eureka clients like the user service and API gateway cannot register to the eureka server because their configuration uses docker compose service name instead of IP. Because each service starts its own docker network, they are not able to see either other at the present time.

Solution:
- [x] Place the services in the same docker network
- [x] Use docker service name to access services

**Comment by tschaffter** [comment]
This error shows that the API gateway can't register to the Eureka server.

```console
2022-06-09 20:51:56.068  INFO 1 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_CHALLENGE-API-GATEWAY/82d184d6ae30:challenge-api-gateway:8082 - was unable to refresh its cache! This periodic background refresh will be retried in 30 seconds. status = Cannot execute request on any known server stacktrace = com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
        at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112)
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134)
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$6.execute(EurekaHttpClientDecorator.java:137)
        at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134)
        at com.netflix.discovery.DiscoveryClient.getAndStoreFullRegistry(DiscoveryClient.java:1101)
        at com.netflix.discovery.DiscoveryClient.fetchRegistry(DiscoveryClient.java:1014)
        at com.netflix.discovery.DiscoveryClient.refreshRegistry(DiscoveryClient.java:1531)
        at com.netflix.discovery.DiscoveryClient$CacheRefreshThread.run(DiscoveryClient.java:1498)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by tschaffter** [comment]
The API gateway can successfully register to the Eureka server using its docker service name when both services are in the same docker network.

Note that the service registry is giving its name to the `challenge` network (see below). It is probably because the network is created when starting this component.

```console
$ docker network inspect challenge
[
    {
        "Name": "challenge",
        "Id": "38e4127a2bd1674c64504feb99a1c203d7f15e6379ad62462655c2a90e7dadde",
        "Created": "2022-06-09T21:46:43.764797Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "192.168.48.0/20",
                    "Gateway": "192.168.48.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "4004af7f983de7616511fd3371ecf6a5040c48ba09df3752b865ae63212bfc07": {
                "Name": "challenge-api-gateway",
                "EndpointID": "2b58e236eefde0bf12ead4d9c6fcfcb36f3111615a8b75758fed88a80761a002",
                "MacAddress": "02:42:c0:a8:30:03",
                "IPv4Address": "192.168.48.3/20",
                "IPv6Address": ""
            },
            "c732b9e62e4ab30a4295a83c6a7795cdc60c2211762a856335d16e45c4298594": {
                "Name": "challenge-postgresql",
                "EndpointID": "e407dae24db499205909b4e57dfc0d4f50effb2b25662cb26f163a6a3e69561a",
                "MacAddress": "02:42:c0:a8:30:04",
                "IPv4Address": "192.168.48.4/20",
                "IPv6Address": ""
            },
            "cbdc905ef8e8bddd4e3eb00fc145eee53e2e47ee2d5ad77950806c402fa03fe7": {
                "Name": "challenge-service-registry",
                "EndpointID": "2f4b32595a81786e533b64f9f79c4e83a1cbb707b00217fc5bce71770143fa3c",
                "MacAddress": "02:42:c0:a8:30:02",
                "IPv4Address": "192.168.48.2/20",
                "IPv6Address": ""
            },
            "d7cced5b67e0809cb1a13450b9f4f8d4e5e02a4878eeaadb9e161d85b6343689": {
                "Name": "challenge-keycloak",
                "EndpointID": "bf0e9acf22fea92467c8b6ac0ca8fc7828ebefdb854da84111c4fe6bdb0c9fb2",
                "MacAddress": "02:42:c0:a8:30:05",
                "IPv4Address": "192.168.48.5/20",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {
            "com.docker.compose.network": "challenge",
            "com.docker.compose.project": "challenge-service-registry",
            "com.docker.compose.version": "2.4.1"
        }
    }
]
```

**Comment by tschaffter** [comment]
If needed, the network could be created manually with `docker network create -d bridge challenge`.
