### ISSUE TITLE
Fix `Error: ENOSPC: System limit for number of file watchers reached, watch '/workspaces/challenge-registry/apps'`

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#449]
VS Code told me about this error for the second time today. The dialog provides [this link](https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc) to help solving the issue.

The result is that I can no longer starts the web app:

```console
$ nx serve challenge-registry

...
>  NX   Successfully ran target build for 1 projects

   Nx read the output from the cache instead of running the command for 1 out of 1 tasks.

⠙ Generating browser application bundles (phase: setup)...node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^

Error: ENOSPC: System limit for number of file watchers reached, watch '/workspaces/challenge-registry/apps'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:2264:34)
    at createFsWatchInstance (/workspaces/challenge-registry/node_modules/chokidar/lib/nodefs-handler.js:119:15)
    at setFsWatchListener (/workspaces/challenge-registry/node_modules/chokidar/lib/nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (/workspaces/challenge-registry/node_modules/chokidar/lib/nodefs-handler.js:331:14)
    at NodeFsHandler._handleDir (/workspaces/challenge-registry/node_modules/chokidar/lib/nodefs-handler.js:567:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async NodeFsHandler._addToNodeFs (/workspaces/challenge-registry/node_modules/chokidar/lib/nodefs-handler.js:617:16)
    at async /workspaces/challenge-registry/node_modules/chokidar/index.js:451:21
    at async Promise.all (index 0)
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (/workspaces/challenge-registry/node_modules/chokidar/index.js:647:10)
    at NodeFsHandler._addToNodeFs (/workspaces/challenge-registry/node_modules/chokidar/lib/nodefs-handler.js:645:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /workspaces/challenge-registry/node_modules/chokidar/index.js:451:21
    at async Promise.all (index 0) {
  errno: -28,
  syscall: 'watch',
  code: 'ENOSPC',
  path: '/workspaces/challenge-registry/apps',
  filename: '/workspaces/challenge-registry/apps'
}

 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target "challenge-registry:serve" failed

   Failed tasks:
   
   - challenge-registry:serve:development
   
   Hint: run the command with --verbose for more details.
```

**Comment by tschaffter** [comment]
Excellent [description](https://stackoverflow.com/a/58213179) of the issue, how to troubleshoot and solve.

**Comment by tschaffter** [comment]
It looks like the above solution fixed the issue.
