### ISSUE TITLE
Fix `ReferenceError: fetch is not defined`

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#454]
This is an old issue that I first encountered when loading the configuration file of the app at startup to enable [Build once, deploy many](https://12factor.net/codebase). This error appears now that I added files to run the app using SSR (#451 ).

The goal of this ticket is to document the solution, once I remember what it is. :)

`main.server.ts`:

```console
/***************************************************************************************************
 * Initialize the server environment - for example, adding DOM built-in types to the global scope.
 *
 * NOTE:
 * This import must come before any imports (direct or transitive) that rely on DOM built-ins being
 * available, such as `@angular/elements`.
 */
import '@angular/platform-server/init';

import { enableProdMode } from '@angular/core';

// import { environment } from './environments/environment';

// if (environment.production) {
//   enableProdMode();
// }

import {
  AppConfig,
  Environment,
} from '@sagebionetworks/challenge-registry/config';

fetch('/config/config.json')
  .then((response) => response.json() as Promise<AppConfig>)
  .then((config: AppConfig) => {
    if (
      [Environment.Production, Environment.Staging].includes(config.environment)
    ) {
      enableProdMode();
    }
  });

export { AppServerModule } from './app/app.server.module';
export { renderModule } from '@angular/platform-server';
```

Error when running `nx serve-ssr challenge-registry`:

```console
...
Compiled successfully.
/workspaces/challenge-registry/dist/challenge-registry/server/main.js:346
fetch('/config/config.json')
^

ReferenceError: fetch is not defined
    at Module.96206 (/workspaces/challenge-registry/dist/challenge-registry/server/main.js:346:1)
    at __webpack_require__ (/workspaces/challenge-registry/dist/challenge-registry/server/main.js:221888:42)
    at /workspaces/challenge-registry/dist/challenge-registry/server/main.js:222057:70
    at /workspaces/challenge-registry/dist/challenge-registry/server/main.js:222108:3
    at Object.<anonymous> (/workspaces/challenge-registry/dist/challenge-registry/server/main.js:222113:12)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)

A server error has occurred.
node exited with 1 code.
connect ECONNREFUSED 127.0.0.1:36467

 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target serve-ssr for project challenge-registry (20s)
 
    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]
 
   See Nx Cloud run details at https://nx.app/runs/zBKHAAzfIX5
```

**Comment by tschaffter** [comment]
Oddly enough, `main.ts` uses `fetch()` without issue when starting with `nx serve challenge-registry`.

I tried installing and importing `import fetch from 'node-fetch';`. The issue becomes:

```console
Compiled successfully.
Unhandled Promise rejection: Invalid URL ; Zone: <root> ; Task: Promise.then ; Value: TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:372:5)
    at URL.onParseError (node:internal/url:553:9)
    at new URL (node:internal/url:629:5)
    at new Request (/workspaces/challenge-registry/dist/challenge-registry/server/main.js:228327:19)
    at /workspaces/challenge-registry/dist/challenge-registry/server/main.js:227889:23
    at new ZoneAwarePromise (/workspaces/challenge-registry/dist/challenge-registry/server/main.js:100699:23)
    at /workspaces/challenge-registry/dist/challenge-registry/server/main.js:227887:12
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/workspaces/challenge-registry/dist/challenge-registry/server/main.js:229588:24)
    at _next (/workspaces/challenge-registry/dist/challenge-registry/server/main.js:229610:9) {
  input: '/config/config.json',
  code: 'ERR_INVALID_URL'
} TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:372:5)
    at URL.onParseError (node:internal/url:553:9)
    at new URL (node:internal/url:629:5)
    at new Request (/workspaces/challenge-registry/dist/challenge-registry/server/main.js:228327:19)
    at /workspaces/challenge-registry/dist/challenge-registry/server/main.js:227889:23
    at new ZoneAwarePromise (/workspaces/challenge-registry/dist/challenge-registry/server/main.js:100699:23)
    at /workspaces/challenge-registry/dist/challenge-registry/server/main.js:227887:12
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/workspaces/challenge-registry/dist/challenge-registry/server/main.js:229588:24)
    at _next (/workspaces/challenge-registry/dist/challenge-registry/server/main.js:229610:9)
```

**Comment by tschaffter** [comment]
It seems that the package `fetch-node` cannot load local file. I believe the reason `fetch()` works using CSR is because the browser is providing the implementation for `fetch()`. But when using SSR, it may be the server that needs to provide the implementation of `fetch()`.

**Comment by tschaffter** [comment]
Not the issue but good to know.

> Universal does not currently support relative urls but only absolute.

[Source](https://stackoverflow.com/questions/55704526/how-to-make-an-angular-app-witch-universal-ssr-use-dynamic-configurations-from-j)
