### ISSUE TITLE
Use global Maven binary

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#558]
I recently solved the issue of concurrent Maven execution in the context of running the CI workflow (#503). However, this involves running a preparation command that may be difficult to fit in the development workflow or would lead to duplicated operation

Here is the issue encountered:

```console
Exception in thread "main" java.nio.file.NoSuchFileException: /home/vscode/.m2/wrapper/dists/apache-maven-3.8.6-bin/67568434/apache-maven-3.8.6-bin.zip.part
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:429)
        at java.base/sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:266)
        at java.base/java.nio.file.Files.move(Files.java:1432)
        at org.apache.maven.wrapper.Installer.createDist(Installer.java:95)
        at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:151)
        at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:76)
```

Solutions are:

- Add Maven to the dev container and update the `project.json` of maven project so that they use the global maven binary instead of the maven wrapper. This approach does not solve the case where multiple projects attempt to download the same dependency at the same time.
- Try Gradle instead of Maven: Maybe Gradle is better at downloading concurrent dependencies, but this is not guaranteed. I'm also just starting to learn Gradle in the context of a pet project, so I won't use it for now.
- Disable Nx concurrency: grantees to solve the issue at the cost of longer runtime.

**Comment by tschaffter** [comment]
No longer needed. Sticking with Maven wrapper until we transition to Gradle.
