### ISSUE TITLE
Publishing the devcontainer fails because the image does not exist locally

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#599]
```console
Run set -e
  set -e
  
  # Push the image to Docker Hub
  docker push "sagebionetworks/challenge-devcontainer:4287403b"
  shell: /usr/bin/bash -e {0}
  env:
    IMAGE_REPOSITORY: sagebionetworks/challenge-devcontainer
    DEFAULT_BRANCH: main
The push refers to repository [docker.io/sagebionetworks/challenge-devcontainer]
An image does not exist locally with the tag: sagebionetworks/challenge-devcontainer
Error: Process completed with exit code 1.
```

**Comment by tschaffter** [comment]
The first issue is that the image does not build because I don't download `hyperfile` with `curl` properly. The second isssue to fix is that the CI workflow does not properly exit the workflow after the error.

```console
ERROR: failed to solve: executor failed running [/bin/bash -euxo pipefail -c groupadd docker   && apt-get update -qq -y && export DEBIAN_FRONTEND=noninteractive   && apt-get install --no-install-recommends -qq -y     ca-certificates curl git bash-completion gnupg2 lsb-release ssh sudo     python3-pip python-is-python3 openjdk-17-jdk     htop unzip vim wget lsof iproute2   && curl -sL https://deb.nodesource.com/setup_16.x | bash -   && curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg |       gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg   && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" |       tee /etc/apt/sources.list.d/github-cli.list > /dev/null   && curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null   && echo "deb https://ngrok-agent.s3.amazonaws.com/ bullseye main" | tee /etc/apt/sources.list.d/ngrok.list   && apt-get update -qq -y   && apt-get install --no-install-recommends -qq -y     nodejs gh ngrok   && corepack enable yarn   && corepack prepare yarn@3.2.2 --activate   && curl https://raw.githubusercontent.com/nektos/act/v0.2.30/install.sh | bash -   && curl https://github.com/sharkdp/hyperfine/releases/download/v1.14.0/hyperfine_1.14.0_amd64.deb   && dpkg -i hyperfine_1.14.0_amd64.deb   && rm -fr hyperfine_1.14.0_amd64.deb   && apt-get -y autoclean   && apt-get -y autoremove   && rm -rf /var/lib/apt/lists/*   && pip install --no-cache-dir pipenv]: exit code: 2
[75298 ms] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/vsch-runner/container-features/0.247.0-1661278520946/Dockerfile-with-features -t sagebionetworks/challenge-devcontainer:f5a4ecd5 --build-arg imageVersion=bullseye-20211220-slim --build-arg devcontainerVersion=f5a4ecd5 --build-context dev_containers_feature_content_source=/tmp/vsch-runner/container-features/0.247.0-1661278520946 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /home/runner/work/challenge-registry/challenge-registry/tools/devcontainers/challenge-devcontainer/.devcontainer
[75299 ms]     at buildAndExtendImage (/usr/local/lib/node_modules/@vscode/dev-container-cli/dist/spec-node/devContainersSpecCLI.js:20983:11)
[75299 ms]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[75299 ms]     at async buildNamedImageAndExtend (/usr/local/lib/node_modules/@vscode/dev-container-cli/dist/spec-node/devContainersSpecCLI.js:20878:12)
[75299 ms]     at async doBuild (/usr/local/lib/node_modules/@vscode/dev-container-cli/dist/spec-node/devContainersSpecCLI.js:22253:34)
[75299 ms]     at async build (/usr/local/lib/node_modules/@vscode/dev-container-cli/dist/spec-node/devContainersSpecCLI.js:22180:18)
[75312 ms] Exit code 1
```

**Comment by tschaffter** [comment]
TODO:

- [ ] Install `@vscode/dev-container-cli` as part of the devcontainer and remove it from the CI workflow.

**Comment by tschaffter** [comment]
## `devcontainer` returns code 0 after failed image build

```console
./build-image.sh

#0 70.36 Reading package lists...
#0 70.71 E: Unsupported file ./hyperfine_1.14.0_amd64.deb given on commandline
------
ERROR: failed to solve: executor failed running [/bin/bash -euxo pipefail -c groupadd docker   && apt-get update -qq -y && export DEBIAN_FRONTEND=noninteractive   && apt-get install --no-install-recommends -qq -y     ca-certificates curl git bash-completion gnupg2 lsb-release ssh sudo     python3-pip python-is-python3 openjdk-17-jdk     htop unzip vim wget lsof iproute2   && curl -sL https://deb.nodesource.com/setup_16.x | bash -   && curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg |       gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg   && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" |       tee /etc/apt/sources.list.d/github-cli.list > /dev/null   && curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null   && echo "deb https://ngrok-agent.s3.amazonaws.com bullseye main" | tee /etc/apt/sources.list.d/ngrok.list   && apt-get update -qq -y   && apt-get install --no-install-recommends -qq -y     nodejs gh ngrok   && npm install --global yarn@latest   && curl https://raw.githubusercontent.com/nektos/act/v0.2.30/install.sh | bash -   && curl https://github.com/sharkdp/hyperfine/releases/download/v1.14.0/hyperfine_1.14.0_amd64.deb   && apt install ./hyperfine_1.14.0_amd64.deb   && rm -fr hyperfine_1.14.0_amd64.deb   && apt-get -y autoclean   && apt-get -y autoremove   && rm -rf /var/lib/apt/lists/*   && pip install --no-cache-dir pipenv]: exit code: 100
[74684 ms] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/vsch-vscode/container-features/0.247.0-1661286635467/Dockerfile-with-features -t sagebionetworks/challenge-devcontainer:test --no-cache --pull --build-arg imageVersion=bullseye-20211220-slim --build-arg devcontainerVersion=ff081d0a --build-context dev_containers_feature_content_source=/tmp/vsch-vscode/container-features/0.247.0-1661286635467 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /workspaces/challenge-registry/tools/devcontainers/challenge-devcontainer/.devcontainer
[74684 ms]     at buildAndExtendImage (/usr/lib/node_modules/@vscode/dev-container-cli/dist/spec-node/devContainersSpecCLI.js:20983:11)
[74684 ms]     at runMicrotasks (<anonymous>)
[74684 ms]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[74684 ms]     at async buildNamedImageAndExtend (/usr/lib/node_modules/@vscode/dev-container-cli/dist/spec-node/devContainersSpecCLI.js:20878:12)
[74684 ms]     at async doBuild (/usr/lib/node_modules/@vscode/dev-container-cli/dist/spec-node/devContainersSpecCLI.js:22253:34)
[74684 ms]     at async build (/usr/lib/node_modules/@vscode/dev-container-cli/dist/spec-node/devContainersSpecCLI.js:22180:18)
[74687 ms] Exit code 1

$ echo $?
0
```

**Comment by tschaffter** [comment]
The issue has been reported [here](https://github.com/devcontainers/cli/issues/144).
