### ISSUE TITLE
VS Code fails to build the `main` devcontainer

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#637]
Current `main` commit: 32c9434af3372ffcdf0ae00517555226578a32ad

Rebuilding and opening the dev container in VS Code leads to this error:

```console
[1910 ms] Start: Run: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/vsch-tschaffter/container-features/0.251.0-1662490635023 --build-arg _DEV_CONTAINERS_BASE_IMAGE=sagebionetworks/challenge-devcontainer:ff081d0a --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-challenge-registry-33c8de79574d448bbfa608795a7e04bc-features -f /tmp/vsch-tschaffter/container-features/0.251.0-1662490635023/Dockerfile.extended /tmp/__dev-containers-build-empty
[+] Building 4.2s (13/13) FINISHED                                              
 => [internal] load build definition from Dockerfile.extended              0.0s
 => => transferring dockerfile: 530B                                       0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => resolve image config for docker.io/docker/dockerfile:1.4               1.7s
 => [auth] docker/dockerfile:pull token for registry-1.docker.io           0.0s
 => CACHED docker-image://docker.io/docker/dockerfile:1.4@sha256:9ba7531b  0.0s
 => [internal] load .dockerignore                                          0.0s
 => [internal] load build definition from Dockerfile.extended              0.0s
 => [context dev_containers_feature_content_source] load .dockerignore     0.0s
 => => transferring dev_containers_feature_content_source: 2B              0.0s
 => [internal] load metadata for docker.io/sagebionetworks/challenge-devc  0.0s
 => [context dev_containers_feature_content_source] load from client       0.0s
 => => transferring dev_containers_feature_content_source: 26.03kB         0.0s
 => [dev_containers_target_stage 1/3] FROM docker.io/sagebionetworks/chal  0.0s
 => CACHED [dev_containers_target_stage 2/3] COPY --from=dev_containers_f  0.0s
 => ERROR [dev_containers_target_stage 3/3] RUN cd /tmp/build-features/do  2.2s
------                                                                          
 > [dev_containers_target_stage 3/3] RUN cd /tmp/build-features/docker-in-docker_1 && set -a && . ./devcontainer-features.env && set +a && chmod +x ./install.sh && ./install.sh:
#0 0.224 + cd /tmp/build-features/docker-in-docker_1                            
#0 0.224 + set -a                                                               
#0 0.224 + . ./devcontainer-features.env                                        
#0 0.224 ++ VERSION=20.10
#0 0.224 ++ MOBY=true
#0 0.224 ++ DOCKERDASHCOMPOSEVERSION=v1
#0 0.224 + set +a
#0 0.224 + chmod +x ./install.sh
#0 0.228 + ./install.sh
#0 0.693 DOCKER_MOBY_ARCHIVE_VERSION_CODENAMES=buster bullseye bionic focal jammy
#0 0.693 Distro codename  'bullseye'  matched filter  'buster bullseye bionic focal jammy'
#0 0.696 Running apt-get update...
#0 0.739 Get:1 http://security.debian.org/debian-security bullseye-security InRelease [48.4 kB]
#0 0.756 Get:2 http://deb.debian.org/debian bullseye InRelease [116 kB]
#0 0.764 Get:3 https://cli.github.com/packages stable InRelease [3917 B]
#0 0.782 Get:4 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
#0 0.785 Get:5 https://deb.nodesource.com/node_16.x bullseye InRelease [4586 B]
#0 0.822 Get:6 http://security.debian.org/debian-security bullseye-security/main amd64 Packages [180 kB]
#0 0.846 Err:3 https://cli.github.com/packages stable InRelease
#0 0.846   The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 23F3D4EA75716059
#0 0.900 Get:7 https://ngrok-agent.s3.amazonaws.com bullseye InRelease [20.3 kB]
#0 0.918 Get:8 http://deb.debian.org/debian bullseye/main amd64 Packages [8182 kB]
#0 1.063 Get:9 https://deb.nodesource.com/node_16.x bullseye/main amd64 Packages [775 B]
#0 1.097 Get:10 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [2596 B]
#0 1.153 Get:11 https://ngrok-agent.s3.amazonaws.com bullseye/main amd64 Packages [1526 B]
#0 1.837 Reading package lists...
#0 2.198 W: GPG error: https://cli.github.com/packages stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 23F3D4EA75716059
#0 2.198 E: The repository 'https://cli.github.com/packages stable InRelease' is not signed.
------
error: failed to solve: executor failed running [/bin/bash -euxo pipefail -c cd /tmp/build-features/docker-in-docker_1 && set -a && . ./devcontainer-features.env && set +a && chmod +x ./install.sh && ./install.sh]: exit code: 100
[6478 ms] Error: Command failed: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/vsch-tschaffter/container-features/0.251.0-1662490635023 --build-arg _DEV_CONTAINERS_BASE_IMAGE=sagebionetworks/challenge-devcontainer:ff081d0a --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-challenge-registry-33c8de79574d448bbfa608795a7e04bc-features -f /tmp/vsch-tschaffter/container-features/0.251.0-1662490635023/Dockerfile.extended /tmp/__dev-containers-build-empty
[6478 ms]     at SF (/home/tschaffter/.vscode-remote-containers/dist/dev-containers-cli-0.251.0/dist/spec-node/devContainersSpecCLI.js:257:2186)
[6478 ms]     at pb (/home/tschaffter/.vscode-remote-containers/dist/dev-containers-cli-0.251.0/dist/spec-node/devContainersSpecCLI.js:257:2124)
[6478 ms]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[6478 ms]     at async DF (/home/tschaffter/.vscode-remote-containers/dist/dev-containers-cli-0.251.0/dist/spec-node/devContainersSpecCLI.js:263:2006)
[6479 ms]     at async to (/home/tschaffter/.vscode-remote-containers/dist/dev-containers-cli-0.251.0/dist/spec-node/devContainersSpecCLI.js:263:3110)
[6479 ms]     at async Ak (/home/tschaffter/.vscode-remote-containers/dist/dev-containers-cli-0.251.0/dist/spec-node/devContainersSpecCLI.js:383:8108)
[6479 ms]     at async Ok (/home/tschaffter/.vscode-remote-containers/dist/dev-containers-cli-0.251.0/dist/spec-node/devContainersSpecCLI.js:383:7864)
[6480 ms] Exit code 1
[6483 ms] Command failed: /home/tschaffter/.vscode-remote-containers/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/node /home/tschaffter/.vscode-remote-containers/dist/dev-containers-cli-0.251.0/dist/spec-node/devContainersSpecCLI.js up --workspace-folder /home/tschaffter/dev2/tschaffter/challenge-registry --workspace-mount-consistency cached --id-label devcontainer.local_folder=\\wsl$\Debian\home\tschaffter\dev2\tschaffter\challenge-registry --log-level debug --log-format json --config /home/tschaffter/dev2/tschaffter/challenge-registry/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[6483 ms] Exit code 1
```

**Comment by tschaffter** [comment]
`apt-get update` fails when using the base Docker image `sagebionetworks/challenge-devcontainer:ff081d0a` because of GH CLI (GPG key no longer valid?). VS Code build the dev container successfully using a fresh base image. I'll push a fresh base image to Docker Hub shortly.

**Comment by tschaffter** [comment]
The issue may happen again. If it's because of GH CLI again, then we can think more about preventing this tool to break the devcontainer.
