### ISSUE TITLE
Migrate to OAS 3.1.0

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#733]
See [Migrating from OpenAPI 3.0 to 3.1.0](https://www.openapis.org/blog/2021/02/16/migrating-from-openapi-3-0-to-3-1-0)

**Comment by tschaffter** [comment]
- The version of Springdoc used support OAS 3.1.0.
- OpenAPI Generator does not support OAS 3.1.0 yet.

  ```console
  $ nx openapi-generate challenge-user-service
  
  > nx run challenge-user-service:openapi-generate
  
  [[challenge-user-service] api-spec/openapi.yaml] [main] ERROR i.s.parser.SwaggerCompatConverter - failed to read resource listing
  [[challenge-user-service] api-spec/openapi.yaml] com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'openapi': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
  [[challenge-user-service] api-spec/openapi.yaml]  at [Source: (String)"openapi: 3.1.0
  [[challenge-user-service] api-spec/openapi.yaml] info:
  [[challenge-user-service] api-spec/openapi.yaml]   title: Challenge User API
  [[challenge-user-service] api-spec/openapi.yaml]   description: This is the User Service of the Challenge Registry.
  [[challenge-user-service] api-spec/openapi.yaml]   termsOfService: TOC
  [[challenge-user-service] api-spec/openapi.yaml]   contact:
  [[challenge-user-service] api-spec/openapi.yaml]     name: The Challenge Registry Team
  [[challenge-user-service] api-spec/openapi.yaml]     url: https://github.com/Sage-Bionetworks/challenge-registry
  [[challenge-user-service] api-spec/openapi.yaml]   license:
  [[challenge-user-service] api-spec/openapi.yaml]     name: Apache 2.0
  [[challenge-user-service] api-spec/openapi.yaml]     url: https://github.com/Sage-Bionetworks/challenge-registry/blob/main/LICENSE.txt
  [[challenge-user-service] api-spec/openapi.yaml]   version: 1.0.0
  [[challenge-user-service] api-spec/openapi.yaml] servers:
  [[challenge-user-service] api-spec/openapi.yaml]   - url: http://localhost:8083
  [[challenge-user-service] api-spec/openapi.yaml]     description: Local server url
  [[challenge-user-service] api-spec/openapi.yaml] tags:
  [[challenge-user-service] api-spec/openapi.yaml]   - name: User
  [[challenge-user-service] api-spec/openapi.yaml]     description: Op"[truncated 3365 chars]; line: 1, column: 8]
  [[challenge-user-service] api-spec/openapi.yaml]        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2391)
  [[challenge-user-service] api-spec/openapi.yaml]        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:745)
  [[challenge-user-service] api-spec/openapi.yaml]        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2961)
  [[challenge-user-service] api-spec/openapi.yaml]        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:2002)
  [[challenge-user-service] api-spec/openapi.yaml]        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:802)
  [[challenge-user-service] api-spec/openapi.yaml]        at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4703)
  [[challenge-user-service] api-spec/openapi.yaml]        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3076)
  [[challenge-user-service] api-spec/openapi.yaml]        at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:209)
  [[challenge-user-service] api-spec/openapi.yaml]        at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:122)
  [[challenge-user-service] api-spec/openapi.yaml]        at io.swagger.parser.SwaggerCompatConverter.readWithInfo(SwaggerCompatConverter.java:93)
  [[challenge-user-service] api-spec/openapi.yaml]        at io.swagger.parser.SwaggerParser.readWithInfo(SwaggerParser.java:44)
  [[challenge-user-service] api-spec/openapi.yaml]        at io.swagger.v3.parser.converter.SwaggerConverter.readLocation(SwaggerConverter.java:90)
  [[challenge-user-service] api-spec/openapi.yaml]        at io.swagger.parser.OpenAPIParser.readLocation(OpenAPIParser.java:16)
  [[challenge-user-service] api-spec/openapi.yaml]        at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:573)
  [[challenge-user-service] api-spec/openapi.yaml]        at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:631)
  [[challenge-user-service] api-spec/openapi.yaml]        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:457)
  [[challenge-user-service] api-spec/openapi.yaml]        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
  [[challenge-user-service] api-spec/openapi.yaml]        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
  [[challenge-user-service] api-spec/openapi.yaml] [main] ERROR i.s.parser.SwaggerCompatConverter - failed to read resource listing
  [[challenge-user-service] api-spec/openapi.yaml] com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'openapi': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
  [[challenge-user-service] api-spec/openapi.yaml]  at [Source: (String)"openapi: 3.1.0
  [[challenge-user-service] api-spec/openapi.yaml] info:
  [[challenge-user-service] api-spec/openapi.yaml]   title: Challenge User API
  [[challenge-user-service] api-spec/openapi.yaml]   description: This is the User Service of the Challenge Registry.
  [[challenge-user-service] api-spec/openapi.yaml]   termsOfService: TOC
  [[challenge-user-service] api-spec/openapi.yaml]   contact:
  [[challenge-user-service] api-spec/openapi.yaml]     name: The Challenge Registry Team
  [[challenge-user-service] api-spec/openapi.yaml]     url: https://github.com/Sage-Bionetworks/challenge-registry
  [[challenge-user-service] api-spec/openapi.yaml]   license:
  [[challenge-user-service] api-spec/openapi.yaml]     name: Apache 2.0
  [[challenge-user-service] api-spec/openapi.yaml]     url: https://github.com/Sage-Bionetworks/challenge-registry/blob/main/LICENSE.txt
  [[challenge-user-service] api-spec/openapi.yaml]   version: 1.0.0
  [[challenge-user-service] api-spec/openapi.yaml] servers:
  [[challenge-user-service] api-spec/openapi.yaml]   - url: http://localhost:8083
  [[challenge-user-service] api-spec/openapi.yaml]     description: Local server url
  [[challenge-user-service] api-spec/openapi.yaml] tags:
  [[challenge-user-service] api-spec/openapi.yaml]   - name: User
  [[challenge-user-service] api-spec/openapi.yaml]     description: Op"[truncated 3365 chars]; line: 1, column: 8]
  [[challenge-user-service] api-spec/openapi.yaml]        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2391)
  [[challenge-user-service] api-spec/openapi.yaml]        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:745)
  [[challenge-user-service] api-spec/openapi.yaml]        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2961)
  [[challenge-user-service] api-spec/openapi.yaml]        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:2002)
  [[challenge-user-service] api-spec/openapi.yaml]        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:802)
  [[challenge-user-service] api-spec/openapi.yaml]        at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4703)
  [[challenge-user-service] api-spec/openapi.yaml]        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3076)
  [[challenge-user-service] api-spec/openapi.yaml]        at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:209)
  [[challenge-user-service] api-spec/openapi.yaml]        at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:122)
  [[challenge-user-service] api-spec/openapi.yaml]        at io.swagger.parser.SwaggerCompatConverter.readWithInfo(SwaggerCompatConverter.java:93)
  [[challenge-user-service] api-spec/openapi.yaml]        at io.swagger.parser.SwaggerParser.readWithInfo(SwaggerParser.java:44)
  [[challenge-user-service] api-spec/openapi.yaml]        at io.swagger.v3.parser.converter.SwaggerConverter.readLocation(SwaggerConverter.java:90)
  [[challenge-user-service] api-spec/openapi.yaml]        at io.swagger.parser.OpenAPIParser.readLocation(OpenAPIParser.java:16)
  [[challenge-user-service] api-spec/openapi.yaml]        at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:573)
  [[challenge-user-service] api-spec/openapi.yaml]        at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:631)
  [[challenge-user-service] api-spec/openapi.yaml]        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:457)
  [[challenge-user-service] api-spec/openapi.yaml]        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
  [[challenge-user-service] api-spec/openapi.yaml]        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
  [[challenge-user-service] api-spec/openapi.yaml] [main] INFO  o.o.codegen.DefaultGenerator - Generating with dryRun=false
  [[challenge-user-service] api-spec/openapi.yaml] Exception in thread "main" java.lang.RuntimeException: Issues with the OpenAPI input. Possible causes: invalid/missing spec, malformed JSON/YAML files, etc.
  [[challenge-user-service] api-spec/openapi.yaml]        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:877)
  [[challenge-user-service] api-spec/openapi.yaml]        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:465)
  [[challenge-user-service] api-spec/openapi.yaml]        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
  [[challenge-user-service] api-spec/openapi.yaml]        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
  [[challenge-user-service] api-spec/openapi.yaml] java -jar "/workspaces/challenge-registry/node_modules/@openapitools/openapi-generator-cli/versions/6.1.0.jar" generate --input-spec="api-spec/openapi.yaml" --config="templates/config.yaml" --generator-name="spring" --output="/workspaces/challenge-registry/apps/challenge-user-service" --template-dir="templates" --additional-properties="apiPackage=org.sagebionetworks.challenge.api,basePackage=org.sagebionetworks.challenge,configPackage=org.sagebionetworks.challenge.configuration,delegatePattern=true,hideGenerationTimestamp=true,library=spring-boot,modelPackage=org.sagebionetworks.challenge.model.dto,useTags=true,modelNameSuffix=Dto" exited with code 1
  [challenge-user-service] api-spec/openapi.yaml
    java -jar "/workspaces/challenge-registry/node_modules/@openapitools/openapi-generator-cli/versions/6.1.0.jar" generate --input-spec="api-spec/openapi.yaml" --config="templates/config.yaml" --generator-name="spring" --output="/workspaces/challenge-registry/apps/challenge-user-service" --template-dir="templates" --additional-properties="apiPackage=org.sagebionetworks.challenge.api,basePackage=org.sagebionetworks.challenge,configPackage=org.sagebionetworks.challenge.configuration,delegatePattern=true,hideGenerationTimestamp=true,library=spring-boot,modelPackage=org.sagebionetworks.challenge.model.dto,useTags=true,modelNameSuffix=Dto"
  
  Code generation failed
  
   >  NX   ERROR: Something went wrong in run-commands - Command failed: openapi-generator-cli generate
  
     Pass --verbose to see the stacktrace.
  
  
   ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
  
   >  NX   Ran target openapi-generate for project challenge-user-service (5s)
   
      ✖    1/1 failed
      ✔    0/1 succeeded [0 read from cache]
  ```

**Comment by tschaffter** [comment]
Monitoring the above ticket.
