### ISSUE TITLE
Format YAML files when saving

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#741]
The goal of this task is to format YAML files (e.g. config files, OpenAPI schemas) when saving them. The solution can be built upon the solution implemented for Java files in #719.

**Comment by tschaffter** [comment]
I initially considered using the ESLint Nx executor with the Prettier plugin, however a quick attempts failed. This [article](https://blog.logrocket.com/using-prettier-eslint-automate-formatting-fixing-javascript/) describes why using ESLint as a wrapper to run Prettier is a bad idea.

> 1. Formatting issues reported as problems by ESLint
> 2. It is a bit slower than running Prettier directly
> 3. You have another layer where bugs can be introduced

**Comment by tschaffter** [comment]
Options considered:

- Run `prettier` directly
- Format using [Spotless](https://github.com/diffplug/spotless) but this may be difficult for projects that don't use Gradle like `api-spec`

**Comment by tschaffter** [comment]
Prettier can not solve SyntaxError on its own. Here using the Prettier extension for VS Code (see red button below).

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/3056480/192656636-47f7618a-b4d7-4af1-b772-da1d9fc93e03.png">

**Comment by tschaffter** [comment]
The VS Code extension uses the `prettier` binary found in the path, instead of shipping with its own version of Prettier. This is great because Prettier should give the same result whether it is run via the VS Code extension or via the command line (git hooks, CI/CD workflow).

This is confirmed by the following error from the VS Code extension after uninstalling `prettier`.

```console
["ERROR" - 2:07:50 AM] Failed to load module. If you have prettier or plugins referenced in package.json, ensure you have run `npm install`
["ERROR" - 2:07:50 AM] Cannot find module 'prettier' from '/workspaces/challenge-registry'
Error: Cannot find module 'prettier' from '/workspaces/challenge-registry'
	at Function.e.exports [as sync] (/home/vscode/.vscode-server/extensions/esbenp.prettier-vscode-9.9.0/dist/extension.js:1:37040)
	at t.ModuleResolver.findPkg (/home/vscode/.vscode-server/extensions/esbenp.prettier-vscode-9.9.0/dist/extension.js:1:7291)
	at t.ModuleResolver.getPrettierInstance (/home/vscode/.vscode-server/extensions/esbenp.prettier-vscode-9.9.0/dist/extension.js:1:3251)
	at t.default.format (/home/vscode/.vscode-server/extensions/esbenp.prettier-vscode-9.9.0/dist/extension.js:1:13317)
	at async t.PrettierEditProvider.provideEdits (/home/vscode/.vscode-server/extensions/esbenp.prettier-vscode-9.9.0/dist/extension.js:1:11197)
	at async x.provideDocumentFormattingEdits (/vscode/vscode-server/bin/linux-x64/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/workbench/api/node/extensionHostProcess.js:87:45865)
["ERROR" - 2:07:50 AM] Prettier could not be loaded. See previous logs for more information.
```
