### ISSUE TITLE
Identify how to run Probot locally and in watch mode

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#752]
This will allow to quickly test new code.

**Comment by tschaffter** [comment]
See `nodemon` command in https://andrewlock.net/creating-my-first-github-app-with-probot-part-1-create-probot-app/

**Comment by tschaffter** [comment]
Using `nodemon ts-node` from [this example](https://github.com/bobvanderlinden/check-reporter/blob/master/package.json) leads to the following error:

```console
nodemon ts-node apps/challenge-bot/src/app.ts
[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts,json
[nodemon] starting `ts-node ts-node apps/challenge-bot/src/app.ts`
node:internal/modules/cjs/loader:959
  throw err;
  ^

Error: Cannot find module './ts-node'
Require stack:
- /workspaces/challenge-registry/imaginaryUncacheableRequireResolveScript
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at requireResolveNonCached (/workspaces/challenge-registry/node_modules/ts-node/dist/bin.js:496:16)
    at getProjectSearchDir (/workspaces/challenge-registry/node_modules/ts-node/dist/bin.js:466:40)
    at phase3 (/workspaces/challenge-registry/node_modules/ts-node/dist/bin.js:268:27)
    at bootstrap (/workspaces/challenge-registry/node_modules/ts-node/dist/bin.js:44:30)
    at main (/workspaces/challenge-registry/node_modules/ts-node/dist/bin.js:32:12)
    at Object.<anonymous> (/workspaces/challenge-registry/node_modules/ts-node/dist/bin.js:526:5)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/workspaces/challenge-registry/imaginaryUncacheableRequireResolveScript'
  ]
}
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by tschaffter** [comment]
Building the app in watch mode: `tsc -p tsconfig.app.json --watch`

**Comment by tschaffter** [comment]
## Certificate issue

Running `nodemon src/index.ts` from the app folder and opening an issue in https://github.com/tschaffter/plop works.

```console
$ nodemon src/index.ts
[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts,json
[nodemon] starting `ts-node src/index.ts`
INFO (server): Running Probot v12.2.8 (Node.js: v16.17.0)
INFO (server): Forwarding https://smee.io/xxx to http://localhost:3000/
INFO (server): Listening on http://localhost:3000
INFO (server): Connected
INFO (http): POST / 200 - 7ms
INFO (server): POST http://localhost:3000/ - 200
DEBUG (octokit): GitHub request: POST https://api.github.com/repos/tschaffter/plop/issues/21/comments - 201
    body: "Thanks for opening this issue!"
INFO (http): POST / 200 - 740ms
INFO (server): POST http://localhost:3000/ - 200
```

But wrapping this command in `nx serve challenge-bot` does not work:

```console
DEBUG (octokit): GitHub request: POST https://api.github.com/repos/tschaffter/plop/issues/20/comments - 401
    body: "Thanks for opening this issue!"
ERROR (HttpError): Your private key (a .pem file or PRIVATE_KEY environment variable) or APP_ID is incorrect. Go to https://github.com/settings/apps/YOUR_APP, verify that APP_ID is set correctly, and generate a new PEM file if necessary.
    HttpError: A JSON web token could not be decoded
```

This means that config properties like `WEBHOOK_PROXY_URL` are correctly read from `.env`. But not `PRIVATE_KEY_PATH`?

**Comment by tschaffter** [comment]
## Checking that the variables in `.env` are correctly exported by Nx

Add the following task to the project.json

```json
    "plop": {
      "executor": "nx:run-commands",
      "options": {
        "command": "echo $PRIVATE_KEY_PATH",
        "cwd": "apps/challenge-bot"
      }
    },
```

Run `nx plop challenge-bot`:

```console
$ nx plop challenge-bot

> nx run challenge-bot:plop

/workspaces/challenge-registry/apps/challenge-bot/cert.pem

 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Successfully ran target plop for project challenge-bot (275ms)
 
   See Nx Cloud run details at https://cloud.nx.app/runs/EB6rIGM1kmP
```

The value of `PRIVATE_KEY_PATH` is correctly set.

**Comment by tschaffter** [comment]
Probot does actually complains if it does not find the path to the private key:

```console
$ nodemon src/index.ts
[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts,json
[nodemon] starting `ts-node src/index.ts`
INFO (probot): 
INFO (probot): Welcome to Probot!
INFO (probot): Probot is in setup mode, webhooks cannot be received and
INFO (probot): custom routes will not work until APP_ID and PRIVATE_KEY
INFO (probot): are configured in .env.
INFO (probot): Please follow the instructions at http://localhost:3000 to configure .env.
INFO (probot): Once you are done, restart the server.
INFO (probot): 
INFO (server): Running Probot v12.2.8 (Node.js: v16.17.0)
INFO (server): Forwarding https://smee.io/xxx to http://localhost:3000/
INFO (server): Listening on http://localhost:3000
INFO (server): Connected
```

**Comment by tschaffter** [comment]
## Observations

- `nx serve challenge-bot` correctly reads the content of `.env` and the values are available in `index.ts`.
- Mystery: if `.env` is empty, `nx serve challenge-bot` still has access to some environment variable values that are nowhere on file AFAIK. Does Nx cache env values and when?
- Mystery: `nx serve challenge-bot` successfully connects even when the path to the certificate is wrong. When running `nodemon src/index.ts`, an error is thrown when the path to the certificate is incorrect and the message for successful connection is not shown.
