### ISSUE TITLE
Fix CI issue `TAR_BAD_ARCHIVE`

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#83]
[The issue](https://github.com/Sage-Bionetworks/challenge-registry/runs/5520288017?check_suite_focus=true) started today. It only affects when merging to the `main` branch..

```console
Run yarn nx affected --target=lint --parallel --max-parallel=3
yarn run v1.22.17
$ /home/runner/work/challenge-registry/challenge-registry/node_modules/.bin/nx affected --target=lint --parallel --max-parallel=3

 >  NX   No explicit --base argument provided, but found environment variable NX_BASE so using its value as the affected base: 367f0b1677822ea9b3d6a3bc103b672b2e7e53e7


 >  NX   No explicit --head argument provided, but found environment variable NX_HEAD so using its value as the affected head: 9ec712f6f7259edeb844acdd5515b3a12af37f2c


 >  NX   Running target lint for 12 project(s):

    - web-app
    - web-app-e2e
    - web-config
    - web-pages
    - web-feature-home
    - web-ui
    - api
    - api-angular
    - api-spec
    - db-cli
    - shared-web-components
    - web-data-access

 
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: TAR_BAD_ARCHIVE: Unrecognized archive format
    at Unpack.warn (/home/runner/work/challenge-registry/challenge-registry/node_modules/tar/lib/warn-mixin.js:19:40)
    at Unpack.warn (/home/runner/work/challenge-registry/challenge-registry/node_modules/tar/lib/unpack.js:220:18)
    at Unpack.<anonymous> (/home/runner/work/challenge-registry/challenge-registry/node_modules/tar/lib/parse.js:81:14)
    at Unpack.emit (events.js:412:35)
    at Unpack.[emit] (/home/runner/work/challenge-registry/challenge-registry/node_modules/tar/lib/parse.js:285:12)
    at Unpack.[maybeEnd] (/home/runner/work/challenge-registry/challenge-registry/node_modules/tar/lib/parse.js:401:17)
    at Unpack.[consumeChunk] (/home/runner/work/challenge-registry/challenge-registry/node_modules/tar/lib/parse.js:432:21)
    at Unpack.write (/home/runner/work/challenge-registry/challenge-registry/node_modules/tar/lib/parse.js:364:25)
    at Unpack.end (/home/runner/work/challenge-registry/challenge-registry/node_modules/tar/lib/parse.js:477:14)
    at IncomingMessage.onend (internal/streams/readable.js:670:10)
Emitted 'error' event on Unpack instance at:
    at Unpack.onerror (internal/streams/readable.js:750:14)
    at Unpack.emit (events.js:400:28)
    at Unpack.warn (/home/runner/work/challenge-registry/challenge-registry/node_modules/tar/lib/warn-mixin.js:19:12)
    at Unpack.warn (/home/runner/work/challenge-registry/challenge-registry/node_modules/tar/lib/unpack.js:220:18)
    [... lines matching original stack trace ...]
    at Unpack.write (/home/runner/work/challenge-registry/challenge-registry/node_modules/tar/lib/parse.js:364:25) {
  recoverable: false,
  cwd: '/home/runner/work/challenge-registry/challenge-registry/node_modules/.cache/nx',
  code: 'TAR_BAD_ARCHIVE',
  tarCode: 'TAR_BAD_ARCHIVE'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

**Comment by tschaffter** [comment]
The folder `node_modules/.cache/nx` contains archives. On my host:

```console
$ ls node_modules/.cache/nx
40ec7da08bd3711b1634935d0df51f1eda4485f2cad47b495cb61c6ba3f0004c         8b9d963e87bbbea67417836ed24c9189e0187d45e380ac9f62d9480114bb5863         f2eaf02f51683e9b560a20ba6d63cfd6c6bd253e7208df1ae1508ca71b978236.tar.gz
40ec7da08bd3711b1634935d0df51f1eda4485f2cad47b495cb61c6ba3f0004c.commit  8b9d963e87bbbea67417836ed24c9189e0187d45e380ac9f62d9480114bb5863.commit  f5d6988930f63df46bc4f09297e87e7566f45d7f40e3666edb4564d8fa4260a9
40ec7da08bd3711b1634935d0df51f1eda4485f2cad47b495cb61c6ba3f0004c.tar.gz  8b9d963e87bbbea67417836ed24c9189e0187d45e380ac9f62d9480114bb5863.tar.gz  f5d6988930f63df46bc4f09297e87e7566f45d7f40e3666edb4564d8fa4260a9.commit
60279f8de0f469a935969cdd8a88551aa64124df3a6540fe3aa9dc9603827292         a016b732e59954003a4e7e203d48f84113fb68231540835bb00a26b70d14a14d         f5d6988930f63df46bc4f09297e87e7566f45d7f40e3666edb4564d8fa4260a9.tar.gz
60279f8de0f469a935969cdd8a88551aa64124df3a6540fe3aa9dc9603827292.commit  a016b732e59954003a4e7e203d48f84113fb68231540835bb00a26b70d14a14d.commit  latestOutputsHashes
60279f8de0f469a935969cdd8a88551aa64124df3a6540fe3aa9dc9603827292.tar.gz  a016b732e59954003a4e7e203d48f84113fb68231540835bb00a26b70d14a14d.tar.gz  nxdeps.json
64bd759465adb501c84449ae3e17d9df66107920235ed84dfd127ff3e37aea42         d                                                                        terminalOutputs
64bd759465adb501c84449ae3e17d9df66107920235ed84dfd127ff3e37aea42.commit  f2eaf02f51683e9b560a20ba6d63cfd6c6bd253e7208df1ae1508ca71b978236
64bd759465adb501c84449ae3e17d9df66107920235ed84dfd127ff3e37aea42.tar.gz  f2eaf02f51683e9b560a20ba6d63cfd6c6bd253e7208df1ae1508ca71b978236.commit
```

**Comment by tschaffter** [comment]
## Update

Specifying the option `--skip-nx-cache` to the nx commands in the CI workflow for the `main` branch solved the issue. I'm still not sure why this issue arose and why only for the `main` branch.

See https://nx.dev/using-nx/caching#skipping-cache
