### ISSUE TITLE
Fix server-side rendering

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#880]
Last time I tried to start the registry with SSR it didn't work.

**Comment by tschaffter** [comment]
This error is thrown when I open the registry in the browser:

```console
$ nx serve-ssr challenge-registry
...

Compiled successfully.
** Angular Universal Live Development Server is listening on http://localhost:4200, open your browser on http://localhost:4200 **
ERROR ReferenceError: window is not defined
    at Array.<anonymous> (/workspaces/challenge-registry/dist/apps/challenge-registry/server/main.js:101218:40)
    at ApplicationInitStatus.runInitializers (/workspaces/challenge-registry/dist/apps/challenge-registry/server/main.js:198384:44)
    at /workspaces/challenge-registry/dist/apps/challenge-registry/server/main.js:200291:20
    at _callAndReportToErrorHandler (/workspaces/challenge-registry/dist/apps/challenge-registry/server/main.js:200444:20)
    at /workspaces/challenge-registry/dist/apps/challenge-registry/server/main.js:200289:14
    at _ZoneDelegate.invoke (/workspaces/challenge-registry/dist/apps/challenge-registry/server/main.js:98157:160)
    at Object.onInvoke (/workspaces/challenge-registry/dist/apps/challenge-registry/server/main.js:199415:25)
    at _ZoneDelegate.invoke (/workspaces/challenge-registry/dist/apps/challenge-registry/server/main.js:98157:48)
    at Zone.run (/workspaces/challenge-registry/dist/apps/challenge-registry/server/main.js:97883:37)
    at NgZone.run (/workspaces/challenge-registry/dist/apps/challenge-registry/server/main.js:199255:24)

ReferenceError: window is not defined
    at Array.<anonymous> (/workspaces/challenge-registry/dist/apps/challenge-registry/server/main.js:101218:40)
    at ApplicationInitStatus.runInitializers (/workspaces/challenge-registry/dist/apps/challenge-registry/server/main.js:198384:44)
    at /workspaces/challenge-registry/dist/apps/challenge-registry/server/main.js:200291:20
    at _callAndReportToErrorHandler (/workspaces/challenge-registry/dist/apps/challenge-registry/server/main.js:200444:20)
    at /workspaces/challenge-registry/dist/apps/challenge-registry/server/main.js:200289:14
    at _ZoneDelegate.invoke (/workspaces/challenge-registry/dist/apps/challenge-registry/server/main.js:98157:160)
    at Object.onInvoke (/workspaces/challenge-registry/dist/apps/challenge-registry/server/main.js:199415:25)
    at _ZoneDelegate.invoke (/workspaces/challenge-registry/dist/apps/challenge-registry/server/main.js:98157:48)
    at Zone.run (/workspaces/challenge-registry/dist/apps/challenge-registry/server/main.js:97883:37)
    at NgZone.run (/workspaces/challenge-registry/dist/apps/challenge-registry/server/main.js:199255:24)
```

**Comment by tschaffter** [comment]
The way I configure KC in the app relies on window:

```typescript
export function initializeKeycloakFactory(
  configService: ConfigService,
  keycloak: KeycloakService
) {
  return () =>
    keycloak.init({
      config: {
        url: 'http://localhost:8080',
        realm: 'test', // configService.config.keycloakRealm,
        clientId: 'test-client',
        // url: config['KEYCLOAK_URL'] + '/auth',
        // realm: config['KEYCLOAK_REALM'],
        // clientId: config['KEYCLOAK_CLIENT_ID'],
      },
      initOptions: {
        onLoad: 'check-sso',
        silentCheckSsoRedirectUri:
          window.location.origin + '/assets/silent-check-sso.html',
        flow: 'standard',
      },
      bearerExcludedUrls: [],
    });
}
```

**Comment by tschaffter** [comment]
> 1) Avoid referencing window, document and other DOM specific globals

> These globals include window, document, localStorage, indexedDB, setTimeout and setInterval.

Source: [The biggest Angular Universal gotchas, and how to avoid them](https://www.willtaylor.blog/angular-universal-gotchas/)

**Comment by tschaffter** [comment]
There is only one occurrence of `window` that I can replace by a configuration property. Then, there is an issue with `document`.

```console
ReferenceError: document is not defined
    at new Keycloak (/workspaces/challenge-registry/dist/apps/challenge-registry/server/main.js:227690:17)
    at Keycloak (/workspaces/challenge-registry/dist/apps/challenge-registry/server/main.js:227678:12)
    at KeycloakService.<anonymous> (/workspaces/challenge-registry/dist/apps/challenge-registry/server/main.js:227320:79)
    at Generator.next (<anonymous>)
    at /workspaces/challenge-registry/dist/apps/challenge-registry/server/main.js:114:71
    at new ZoneAwarePromise (/workspaces/challenge-registry/dist/apps/challenge-registry/server/main.js:99254:23)
    at __awaiter (/workspaces/challenge-registry/dist/apps/challenge-registry/server/main.js:110:12)
    at KeycloakService.init (/workspaces/challenge-registry/dist/apps/challenge-registry/server/main.js:227314:60)
    at Array.<anonymous> (/workspaces/challenge-registry/dist/apps/challenge-registry/server/main.js:101207:27)
    at ApplicationInitStatus.runInitializers (/workspaces/challenge-registry/dist/apps/challenge-registry/server/main.js:198385:44)
```

**Comment by tschaffter** [comment]
Tired [this solution](https://www.willtaylor.blog/angular-universal-gotchas/) but the app now hangs indefinitely when using `global['document'] = window.document;`.

> Hi @lilletech, we currently do not support running Keycloak in a Universal environment. This is mostly due to the fact that we depend on keycloak-js which is not optimized to run in a NodeJS environment. If you're willing to see if there might be some solution to this feel free to share your thoughts.

Source; https://github.com/mauriciovigolo/keycloak-angular/issues/263#issuecomment-654204421

**Comment by tschaffter** [comment]
After conditionally initializing KC, this error is shown on the server side when loading the app:

```console
ERROR TypeError: Cannot read properties of undefined (reading 'authenticated')
    at KeycloakService.<anonymous> (/workspaces/challenge-registry/dist/apps/challenge-registry/server/main.js:227442:27)
    at Generator.next (<anonymous>)
    at /workspaces/challenge-registry/dist/apps/challenge-registry/server/main.js:114:71
    at new ZoneAwarePromise (/workspaces/challenge-registry/dist/apps/challenge-registry/server/main.js:99254:23)
    at __awaiter (/workspaces/challenge-registry/dist/apps/challenge-registry/server/main.js:110:12)
    at KeycloakService.loadUserProfile (/workspaces/challenge-registry/dist/apps/challenge-registry/server/main.js:227437:60)
    at KAuthService.getUserProfile (/workspaces/challenge-registry/dist/apps/challenge-registry/server/main.js:106986:80)
    at AppComponent.ngOnInit (/workspaces/challenge-registry/dist/apps/challenge-registry/server/main.js:101034:27)
    at callHook (/workspaces/challenge-registry/dist/apps/challenge-registry/server/main.js:171908:14)
    at callHooks (/workspaces/challenge-registry/dist/apps/challenge-registry/server/main.js:171864:9)
```
