### ISSUE TITLE
Figure out how to change an SQL DB seed data with Flyway without having to clear the docker volume of the DB

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#998]
## Current protocol

1. Remove all docker containers and volumes.
2. Start the organization service in development mode: `nx serve challenge-organization-service`.
3. The service should have successfully started and the Swagger UI page should be available at http://localhost:8084.
4. Rename the org "DREAM" to "DREAM2" in `src/main/resources/db/migration/V1.0.20210427174721__temp_data.sql` and save.
5. The service restarts and throws the following error:

```console
Migration checksum mismatch for migration version 1.0.20210427174721
-> Applied to database : -286174695
-> Resolved locally    : -436640458
Either revert the changes to the migration, or run repair to update the schema history.
Need more flexibility with validation rules? Learn more: https://rd.gt/3AbJUZE
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans-5.3.23.jar:5.3.23]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.23.jar:5.3.23]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.23.jar:5.3.23]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.23.jar:5.3.23]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.23.jar:5.3.23]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.23.jar:5.3.23]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.23.jar:5.3.23]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.3.23.jar:5.3.23]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:233) ~[spring-beans-5.3.23.jar:5.3.23]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1284) ~[spring-beans-5.3.23.jar:5.3.23]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1245) ~[spring-beans-5.3.23.jar:5.3.23]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveBean(DefaultListableBeanFactory.java:494) ~[spring-beans-5.3.23.jar:5.3.23]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:349) ~[spring-beans-5.3.23.jar:5.3.23]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:342) ~[spring-beans-5.3.23.jar:5.3.23]
        at org.springframework.orm.jpa.EntityManagerFactoryUtils.findEntityManagerFactory(EntityManagerFactoryUtils.java:121) ~[spring-orm-5.3.23.jar:5.3.23]
        at org.springframework.orm.jpa.EntityManagerFactoryAccessor.setBeanFactory(EntityManagerFactoryAccessor.java:155) ~[spring-orm-5.3.23.jar:5.3.23]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeAwareMethods(AbstractAutowireCapableBeanFactory.java:1826) ~[spring-beans-5.3.23.jar:5.3.23]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1791) ~[spring-beans-5.3.23.jar:5.3.23]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.23.jar:5.3.23]
        ... 118 common frames omitted
Caused by: org.flywaydb.core.api.exception.FlywayValidateException: Validate failed: Migrations have failed validation
Migration checksum mismatch for migration version 1.0.20210427174721
-> Applied to database : -286174695
-> Resolved locally    : -436640458
Either revert the changes to the migration, or run repair to update the schema history.
Need more flexibility with validation rules? Learn more: https://rd.gt/3AbJUZE
        at org.flywaydb.core.Flyway.lambda$migrate$0(Flyway.java:134) ~[flyway-core-9.4.0.jar:na]
        at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:204) ~[flyway-core-9.4.0.jar:na]
        at org.flywaydb.core.Flyway.migrate(Flyway.java:128) ~[flyway-core-9.4.0.jar:na]
        at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66) ~[spring-boot-autoconfigure-2.7.4.jar:2.7.4]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.23.jar:5.3.23]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.23.jar:5.3.23]
        ... 136 common frames omitted
```

## References

- [Database Migrations with Flyway](https://www.baeldung.com/database-migrations-with-flyway)
- [How to reload Initial Data in running Spring Boot applicaiton?](https://stackoverflow.com/questions/63400825/how-to-reload-initial-data-in-running-spring-boot-applicaiton)
- [How to run flyway:clean before migrations in a SpringBoot app?](https://stackoverflow.com/questions/30830441/how-to-run-flywayclean-before-migrations-in-a-springboot-app)
- [One-Stop Guide to Database Migration with Flyway and Spring Boot](https://reflectoring.io/database-migration-spring-boot-flyway/)
- [How to run flyway:clean before migrations in a SpringBoot app?](https://stackoverflow.com/questions/30830441/how-to-run-flywayclean-before-migrations-in-a-springboot-app)

**Comment by tschaffter** [comment]
Get information from Flyway:

```console
vscode@4e2be94b590c:/workspaces/challenge-registry/apps/challenge-organization-service$ ./gradlew flywayInfo

> Task :flywayInfo
Flyway upgrade recommended: MariaDB 10.9 is newer than this version of Flyway and support has not been tested. The latest supported version of MariaDB is 10.6.
Schema version: 1.0.20210427174721
+-----------+--------------------+---------------------------+------+---------------------+---------+
| Category  | Version            | Description               | Type | Installed On        | State   |
+-----------+--------------------+---------------------------+------+---------------------+---------+
| Versioned | 1.0.20210427174638 | create organization table | SQL  | 2022-12-14 19:09:00 | Success |
| Versioned | 1.0.20210427174721 | temp data                 | SQL  | 2022-12-14 19:09:00 | Success |
+-----------+--------------------+---------------------------+------+---------------------+---------+
```

**Comment by tschaffter** [comment]
## Solution 1 (not convenient)

1. Stop the organization service.
2. Fix Flyway data: `./gradlew flywayRepair`
3. Restart the organization service.

**Comment by tschaffter** [comment]
```console
./gradlew flywayMigrate --info
./gradlew flywayUndo
```

**Comment by tschaffter** [comment]
## Solution 2

The solution is described [here](https://gist.github.com/hikoma/c4a339d0b7c893f5450b).

- One variant is to set `spring.flyway.cleanOnValidationError` to `true`.
- Another variant is to create a bean that clean the database when the app reload (see above link).

Both of these approach should be configured to run only during development and not when the service is running in production.

**Comment by tschaffter** [comment]
Why using `FlywayMigrationStrategy` may not work for me:

> We've discussed this one today and concluded that things should be left as they are. FlywayMigrationStrategy is intended for customization of the migration of the auto-configured Flyway bean. If you are defining your own Flyway bean that is a signal that you wish to take control of how the Flyway bean is defined and migrated. If the behaviour was changed as you have proposed, we may break existing applications that are relying on the definition of a Flyway bean allowing them to take this control.

[Source](https://github.com/spring-projects/spring-boot/issues/21436#issuecomment-634737689)
